nxp-lx2xxx: add dpdk package to NON_MULTILIB
Issue: LIN1023-2109

The dpdk userspace package does not support lib32, to avoid below building issue:
ERROR: Nothing RPROVIDES 'lib32-dpdk':
lib32-dpdk was skipped: incompatible with host arm-wrsmllib32-linux-gnueabi (not in COMPATIBLE_HOST)
lib32-dpdk was skipped: incompatible with machine nxp-lx2xxx (not in COMPATIBLE_MACHINE)
lib32-dpdk was skipped: incompatible with machine nxp-lx2xxx (not in COMPATIBLE_MACHINE)
lib32-dpdk was skipped: incompatible with machine nxp-lx2xxx (not in COMPATIBLE_MACHINE)

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>