nxp-lx2xxx: move ceetm to nxp aarch64 package list
Issue: LIN1019-5183

For ceetm(Customer-edge egress-traffic management), which is a
DPAA enhancement for achieving higher throughput using Network
Stack QoS, there will be errors when build multilib package, like:
 ERROR: Task (virtual:multilib:lib32: .../ceetm/ceetm_git.bb:do_compile)
 failed with exit code '1'
 fatal error: gnu/stubs-soft.h: No such file or directory
 |     7 | # include <gnu/stubs-soft.h>

Patially due to the upgrade of GCC, so move it the nxp aarch64 list
to fix this issue.

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>