nxp-lx2xxx: remove depending layer for this BSP
Issue: LIN1022-1940

It's no need to depend the layer meta-imx for this BSP, it's enough to
depend the layer meta-freescale. And to avoid below building error:
layers/meta-imx/meta-sdk/recipes-graphics/libgpuperfcnt/libgpuperfcnt_6.4.3.p4.2.bb:23:
Could not inherit file classes/fsl-eula-unpack2.bbclass
ERROR: Parsing halted due to errors, see error messages above

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>